---
title: Analyse GEO Samples for contamination
output: 
  html_document: default
---

```{r setup, include=FALSE}
source("lib/knitr.R")
library(BioQC)
library(rworldmap)
source("lib/plots.R")
source("lib/db.R")
```


To get an overview, we want to replicate the heatmaps for each tissue that we created in `bulk_analysis_gds.Rmd`. 

```{r, cache=TRUE}
tissues = dbGetQuery(mydb, "select * from bioqc_tissues where id != 'other'")

getTissueSamples = function(tissue, limit=-1) {
  # get all samples belonging to one tissue and filter for siginifant 
  # signatures in one sql query! 
  query = "
  with gsm_rand as (
        select distinct gsm 
        from bioqc_res_fil
        where tissue = ? 
        order by DBMS_RANDOM.RANDOM
  ),
  gsm_rand_lim as (
     select *
     from gsm_rand
     %s
  ),
  significant_signatures as (
    select distinct signature
    from bioqc_res_fil  
    where pvalue < 1e-8
  )
  select /* +parallel(16)*/ * 
  from gsm_rand_lim gr
  join bioqc_res_fil brf on brf.gsm = gr.gsm
  join significant_signatures ss on ss.signature = brf.signature
  "
  if(limit > 0) {
    query = sprintf(query, sprintf("where rownum <= %i", limit))
  } else {
    query = sprintf(query, "")
  }
  data = dbGetQuery(mydb, query, tissue)
  data = data.frame(data, pvalue.log=absLog10p(as.numeric(data[,"PVALUE"])))
  return(data)
}

for(tissue in tissues$ID) {
  data = getTissueSamples(tissue, 300)
  print(tissue)
  hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  
  data$GSM = factor(data$GSM, levels=sample(unique(data$GSM)))  
  the.plot = ggplot(data=data, aes(x=GSM, y=SIGNATURE, fill=pvalue.log)) + geom_tile() +
    coord_equal() +
    scale_fill_gradientn(colours = hm.palette(100)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle(tissue)
  pdf(file=sprintf("results/heatmaps_db/%s.pdf", tissue), width=100, height=15)
  print(the.plot)
  dev.off()
}
```
