require("RJDBC")
source("db/.db_creds.R")
options(java.parameters = "-Xmx4g" )
drv <- RJDBC::JDBC("org.postgresql.Driver", "db/postgresql-9.4.1211.jre7.jar")
con <- dbConnect(drv, sprintf("jdbc:postgresql://%s:5432/%s", pg_server, pg_dbname), user = pg_user, password = pg_pass )
