/** Table Tissues: holds manually selected tissues **/
drop table if exists bioqc_tissues cascade;
create table bioqc_tissues(id varchar(80) not null primary key);

/** 
 * Table GEO Samples: holds additional meta information that is not
 * contained in GEOmetabase (e.g. the processed tissue information)
 */
drop table if exists bioqc_gsm cascade;
create table bioqc_gsm(gsm varchar(10) primary key references gsm(gsm),
    tissue varchar(80) references bioqc_tissues(id),
    tissue_orig text);

drop table if exists bioqc_signatures cascade;
create table bioqc_signatures(id varchar(80) not null primary key,
    gene_symbols text null);

drop table if exists bioqc_tissues_signatures cascade;
create table bioqc_tissues_signatures(tissue varchar(80) references bioqc_tissues(id),
    signature varchar(80) references bioqc_signatures(id),
    primary key(tissue, signature));

drop table if exists bioqc_res cascade;
create table bioqc_res(sample varchar(10) not null primary key references gsm(gsm),
    "Adipose_NGS_RNASEQATLAS_0.6_3" float,
    "Adrenal_NGS_RNASEQATLAS_0.6_3" float,
    "Brain_NGS_RNASEQATLAS_0.6_3" float,
    "Breast_NGS_RNASEQATLAS_0.6_3" float,
    "Colon_NGS_RNASEQATLAS_0.6_3" float,
    "Heart_NGS_RNASEQATLAS_0.6_3" float,
    "Hypothalamus_NGS_RNASEQATLAS_0.6_3" float,
    "Kidney_NGS_RNASEQATLAS_0.6_3" float,
    "Liver_NGS_RNASEQATLAS_0.6_3" float,
    "Lung_NGS_RNASEQATLAS_0.6_3" float,
    "Lymph_node_NGS_RNASEQATLAS_0.6_3" float,
    "Ovary_NGS_RNASEQATLAS_0.6_3" float,
    "Prostate_NGS_RNASEQATLAS_0.6_3" float,
    "Skeletal_Muscle_NGS_RNASEQATLAS_0.6_3" float,
    "Spleen_NGS_RNASEQATLAS_0.6_3" float,
    "Testis_NGS_RNASEQATLAS_0.6_3" float,
    "Thyroid_NGS_RNASEQATLAS_0.6_3" float,
    "WBC_NGS_RNASEQATLAS_0.6_3" float,
    "Adipose_NR_0.7_3" float,
    "Adipose_brown_NR_0.7_3" float,
    "Adipose_omental_NR_0.7_3" float,
    "Adipose_white_NR_0.7_3" float,
    "Adrenal_Cortex_NR_0.7_3" float,
    "Adrenal_Gland_NR_0.7_3" float,
    "Artery_coronary_NR_0.7_3" float,
    "Blood_NR_0.7_3" float,
    "Bone_NR_0.7_3" float,
    "Bone_Marrow_NR_0.7_3" float,
    "Brain_NR_0.7_3" float,
    "Brain_Amygdala_NR_0.7_3" float,
    "Brain_Caudate_nucleus_NR_0.7_3" float,
    "Brain_Cerebellum_NR_0.7_3" float,
    "Brain_Cerebellum_peduncles_NR_0.7_3" float,
    "Brain_Cortex_NR_0.7_3" float,
    "Brain_Cortex_cingulate_NR_0.7_3" float,
    "Brain_Cortex_prefrontal_NR_0.7_3" float,
    "Brain_Globus_pallidus_NR_0.7_3" float,
    "Brain_Hippocampus_NR_0.7_3" float,
    "Brain_Hypothalamus_NR_0.7_3" float,
    "Brain_Nucleus_accumbens_NR_0.7_3" float,
    "Brain_Olfactory_bulb_NR_0.7_3" float,
    "Brain_Striatum_dorsal_NR_0.7_3" float,
    "Brain_Subthalamic_nucleus_NR_0.7_3" float,
    "Brain_Thalamus_NR_0.7_3" float,
    "Brain_fetal_NR_0.7_3" float,
    "Brain_parietal_lobe_NR_0.7_3" float,
    "Brain_stem_Medulla_oblongata_NR_0.7_3" float,
    "Brain_stem_Pons_NR_0.7_3" float,
    "Brain_temporal_lobe_NR_0.7_3" float,
    "Bronchi_NR_0.7_3" float,
    "Ciliary_body_NR_0.7_3" float,
    "Cornea_NR_0.7_3" float,
    "Dendritic_cell_lymphoid_NR_0.7_3" float,
    "Dendritic_cells_NR_0.7_3" float,
    "Dendritic_cells_myeloid_NR_0.7_3" float,
    "Dendritic_cells_plasmacytoid_NR_0.7_3" float,
    "Endometrium_NR_0.7_3" float,
    "Endothelial_Cells_NR_0.7_3" float,
    "Epidermis_NR_0.7_3" float,
    "Epidermis_tongue_NR_0.7_3" float,
    "Epithelial_bronchial_NR_0.7_3" float,
    "Epithelial_retinal_pigment_NR_0.7_3" float,
    "Erythrocyte_progenitor_NR_0.7_3" float,
    "Erythroid_cells_NR_0.7_3" float,
    "Eyecup_NR_0.7_3" float,
    "Ganglion_cervical_sup_NR_0.7_3" float,
    "Ganglion_ciliary_NR_0.7_3" float,
    "Ganglion_root_dorsal_NR_0.7_3" float,
    "Ganglion_trigeminal_NR_0.7_3" float,
    "Granulocyte_INFL_NR_0.7_3" float,
    "Granulocyte_progenitor_NR_0.7_3" float,
    "Hemopoietic_stem_cells_NR_0.7_3" float,
    "Intestine_Appendix_NR_0.7_3" float,
    "Intestine_Colon_NR_0.7_3" float,
    "Intestine_small_NR_0.7_3" float,
    "Iris_NR_0.7_3" float,
    "Kidney_NR_0.7_3" float,
    "Kidney_Renal_Cortex_NR_0.7_3" float,
    "Kidney_Renal_Medulla_NR_0.7_3" float,
    "Lacrimal_Gland_NR_0.7_3" float,
    "Lens_NR_0.7_3" float,
    "Liver_NR_0.7_3" float,
    "Liver_fetal_NR_0.7_3" float,
    "Lung_NR_0.7_3" float,
    "Lung_fetal_NR_0.7_3" float,
    "Lymph_Node_NR_0.7_3" float,
    "Lymphoblast_B_NR_0.7_3" float,
    "Lymphocyte_B_FOLL_NR_0.7_3" float,
    "Lymphocytes_B_MZ_NR_0.7_3" float,
    "Lymphocytes_B_PB_NR_0.7_3" float,
    "Lymphocytes_NK_NR_0.7_3" float,
    "Lymphocytes_NK_PB_NR_0.7_3" float,
    "Lymphocytes_T_CTC_PB_NR_0.7_3" float,
    "Lymphocytes_T_FOXP3_NR_0.7_3" float,
    "Lymphocytes_T_H_NR_0.7_3" float,
    "Lymphocytes_T_PB_NR_0.7_3" float,
    "Lymphocytes_T_Thymus_CD4_NR_0.7_3" float,
    "Lymphocytes_T_Thymus_CD4_CD8_NR_0.7_3" float,
    "Lymphocytes_T_Thymus_CD8_NR_0.7_3" float,
    "Macrophage_BM_NR_0.7_3" float,
    "Macrophage_PB_NR_0.7_3" float,
    "Mammary_NR_0.7_3" float,
    "Mast_cell_PB_NR_0.7_3" float,
    "Microglia_NR_0.7_3" float,
    "Monocytes_NR_0.7_3" float,
    "Muscle_cardiac_NR_0.7_3" float,
    "Muscle_cardiac_atrium_NR_0.7_3" float,
    "Muscle_cardiac_ventricle_NR_0.7_3" float,
    "Muscle_skeletal_NR_0.7_3" float,
    "Muscle_skeletal_tongue_NR_0.7_3" float,
    "Muscle_smooth_NR_0.7_3" float,
    "Myeloblast_NR_0.7_3" float,
    "Myeloid_progenitor_NR_0.7_3" float,
    "Nervous_AV_Node_NR_0.7_3" float,
    "Nipple_NR_0.7_3" float,
    "Nodose_nucleus_NR_0.7_3" float,
    "Oral_mucosa_NR_0.7_3" float,
    "Osteoblast_NR_0.7_3" float,
    "Osteoclast_NR_0.7_3" float,
    "Ovary_NR_0.7_3" float,
    "Pancreas_NR_0.7_3" float,
    "Pancreas_Islets_NR_0.7_3" float,
    "Pharynx_mucosa_NR_0.7_3" float,
    "Pituitary_NR_0.7_3" float,
    "Placenta_NR_0.7_3" float,
    "Prostate_NR_0.7_3" float,
    "Retina_NR_0.7_3" float,
    "Salivary_Gland_NR_0.7_3" float,
    "Saphenous_vein_NR_0.7_3" float,
    "Skin_NR_0.7_3" float,
    "Spinal_cord_NR_0.7_3" float,
    "Spleen_NR_0.7_3" float,
    "Stomach_NR_0.7_3" float,
    "Stomach_cardiac_NR_0.7_3" float,
    "Stomach_fundus_NR_0.7_3" float,
    "Stomach_pyloric_NR_0.7_3" float,
    "Testis_NR_0.7_3" float,
    "Testis_Germ_Cell_NR_0.7_3" float,
    "Testis_Interstitial_NR_0.7_3" float,
    "Testis_Leydig_Cell_NR_0.7_3" float,
    "Testis_Semin_Tubule_NR_0.7_3" float,
    "Thymus_NR_0.7_3" float,
    "Thyroid_NR_0.7_3" float,
    "Thyroid_fetal_NR_0.7_3" float,
    "Tonsils_NR_0.7_3" float,
    "Trachea_NR_0.7_3" float,
    "Umbilical_cord_NR_0.7_3" float,
    "Urethra_NR_0.7_3" float,
    "Urinary_Bladder_NR_0.7_3" float,
    "Uterus_NR_0.7_3" float,
    "Uterus_Body_NR_0.7_3" float,
    "Uterus_Cervix_NR_0.7_3" float,
    "Uterus_Myometrium_NR_0.7_3" float,
    "Vagina_NR_0.7_3" float,
    "Vulva_NR_0.7_3" float);
